version: "3.8"

services:
  backend:
    build: ./backend
    container_name: economic-math-stock-backend-dev
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/economic_math_stock_db
      JWT_SECRET: your_jwt_secret_here
      REDIS_URL: redis://redis:6379
      ENABLE_STOCK_UPDATER: "true"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    command: npm run dev
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: economic-math-stock-db-dev
    environment:
      POSTGRES_DB: economic_math_stock_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: economic-math-stock-redis-dev
    ports:
      - "6380:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data_dev:
  redis_data_dev:
