version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mathematical-economics-postgres
    environment:
      POSTGRES_DB: mathematical_economics
      POSTGRES_USER: mathuser
      POSTGRES_PASSWORD: mathpass123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mathuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: mathematical-economics-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: mathematical-economics-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://mathuser:mathpass123@postgres:5432/mathematical_economics
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-key-here}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your-jwt-refresh-secret-key-here}
      PORT: 5001
      CORS_ORIGIN: http://localhost:3002,http://localhost:5173
    ports:
      - "5002:5001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mathematical-economics-frontend
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:5002/api
    ports:
      - "3002:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data: